id: I1922A904
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T22:54:14+00:00'
last_modified: '2022-06-08T17:08:34.817505+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137841
  title: 中国第二历史档案馆所存西藏和藏事档案汇编
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4472':
      image_group_id: I2PD20448
      title: ''
      total_pages: 574
      order: 1
      base_file: 4472.txt
    3AB4:
      image_group_id: I2PD20449
      title: ''
      total_pages: 550
      order: 2
      base_file: 3AB4.txt
    '3443':
      image_group_id: I2PD20450
      title: ''
      total_pages: 506
      order: 3
      base_file: 3443.txt
    1C67:
      image_group_id: I2PD20451
      title: ''
      total_pages: 514
      order: 4
      base_file: 1C67.txt
    34E4:
      image_group_id: I2PD20452
      title: ''
      total_pages: 514
      order: 5
      base_file: 34E4.txt
    B44F:
      image_group_id: I2PD20453
      title: ''
      total_pages: 526
      order: 6
      base_file: B44F.txt
    BD70:
      image_group_id: I2PD20454
      title: ''
      total_pages: 518
      order: 7
      base_file: BD70.txt
    '2203':
      image_group_id: I2PD20455
      title: ''
      total_pages: 546
      order: 8
      base_file: 2203.txt
    DAE8:
      image_group_id: I2PD20456
      title: ''
      total_pages: 510
      order: 9
      base_file: DAE8.txt
    E29B:
      image_group_id: I2PD20457
      title: ''
      total_pages: 544
      order: 10
      base_file: E29B.txt
    F806:
      image_group_id: I2PD20458
      title: ''
      total_pages: 496
      order: 11
      base_file: F806.txt
    B65E:
      image_group_id: I2PD20459
      title: ''
      total_pages: 506
      order: 12
      base_file: B65E.txt
    48DA:
      image_group_id: I2PD20460
      title: ''
      total_pages: 492
      order: 13
      base_file: 48DA.txt
    4D76:
      image_group_id: I2PD20461
      title: ''
      total_pages: 500
      order: 14
      base_file: 4D76.txt
    644C:
      image_group_id: I2PD20462
      title: ''
      total_pages: 484
      order: 15
      base_file: 644C.txt
    42E6:
      image_group_id: I2PD20463
      title: ''
      total_pages: 502
      order: 16
      base_file: 42E6.txt
    E194:
      image_group_id: I2PD20464
      title: ''
      total_pages: 508
      order: 17
      base_file: E194.txt
    BB11:
      image_group_id: I2PD20465
      title: ''
      total_pages: 500
      order: 18
      base_file: BB11.txt
    91B9:
      image_group_id: I2PD20466
      title: ''
      total_pages: 510
      order: 19
      base_file: 91B9.txt
    94DD:
      image_group_id: I2PD20467
      title: ''
      total_pages: 504
      order: 20
      base_file: 94DD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
